### ISSUE TITLE
AttributeError: module 'ss2' has no attribute 'run'

### ISSUE THREAD

**Issue by kkzzhizhou** [cherusk/prometheus_ss_exporter#1]
![image](https://user-images.githubusercontent.com/17605703/206620195-356e53ed-d918-4a6e-90ec-cfe8a1d668f1.png)

it's not working, please help.

**Comment by kkzzhizhou** [comment]
pyroute2 broke ss2  in 0.7.3 in python3. issue can be closed

**Comment by cherusk** [comment]
I'm glad that you've found the cause.

Either way, I'm willing to help.

**Comment by cherusk** [comment]
To be solved with this PR https://github.com/svinota/pyroute2
